parameters:
  name: ''
  vmImage: ''
  pool: ''
  matrix: []

jobs:
 - job: ${{ parameters.name }}
   pool:
     vmImage: ${{ parameters.vmImage }}
   strategy:
     matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - script: |
        sudo apt-get install qemu
        sudo apt-get install qemu-user
        sudo apt-get install qemu-user-static
        sudo apt-get install qemu-system-arm
      displayName: 'Installing qemu libraries'
    - script: docker run --rm --privileged hypriot/qemu-register
      displayName: 'Regietering qemu'
    - script: |
        export DOCKER_IMAGE=condaforge/linux-anvil-aarch64
        bash buildscripts/incremental/run_docker_build.sh
      displayName: 'Running AArch64 build'
